{
 "title": "CPU Usage Dashboard",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Nodes",
   "type": "stat",
   "description": "Total Number of Nodes",
   "gridPos": { "h": 5, "w": 5, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "count(kube_node_info)", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "CPU Usage Per Node",
   "type": "gauge",
   "description": "Shows the CPU Usage Per Node in our EKS Cluster",
   "gridPos": { "h": 5, "w": 19, "x": 5, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (node) (\r\n  rate(container_cpu_usage_seconds_total{container!=\"\",pod!=\"\"}[5m])\r\n)\r\n/\r\nsum by (node) (\r\n  kube_node_status_allocatable{resource=\"cpu\"}\r\n)\r\n* 100\r\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Namespaces",
   "type": "stat",
   "description": "Shows Total Number of Namespaces",
   "gridPos": { "h": 5, "w": 5, "x": 0, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(kube_namespace_created)\r\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CPU Usage Per Major Namespace",
   "type": "gauge",
   "description": "Includes the namespaces from our EKS Cluster",
   "gridPos": { "h": 5, "w": 19, "x": 5, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (namespace) (\r\n  rate(container_cpu_usage_seconds_total{container!=\"\",pod!=\"\"}[5m])\r\n)\r\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Running Pods",
   "type": "stat",
   "description": "Shows Total Number of Running Pods",
   "gridPos": { "h": 13, "w": 5, "x": 0, "y": 10 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kube_pod_status_phase{phase=\"Running\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Individual Pod CPU Usage",
   "type": "timeseries",
   "description": "Shows CPU Usage for all Pods in our EKS Cluster",
   "gridPos": { "h": 13, "w": 19, "x": 5, "y": 10 },
   "targets": [
    {
     "expr": "sum by (namespace, pod) (\r\n  rate(container_cpu_usage_seconds_total{container!=\"\",pod!=\"\"}[5m])\r\n)\r\n",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}