{
 "title": "Errors Dashboard",
 "time": { "from": "now-30m", "to": "now" },
 "panels": [
  {
   "title": "Pod CrashLoopBackOff Errors",
   "type": "timeseries",
   "description": "Shows the Count of Each Pod in the Dev Namespace Restarting",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "rate(kube_pod_container_status_restarts_total{namespace=\"dev\"}[5m])\r\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Namespace Network Transmit Errors",
   "type": "timeseries",
   "description": "Shows Total Number of Namespace Network Transmit Errors in our EKS Cluster",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum by (namespace) (\r\n  irate(container_network_transmit_errors_total[$__rate_interval])\r\n)\r\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Namespace Network Receive Errors",
   "type": "timeseries",
   "description": "Shows the Total Number of Namespace Network Receive Errors in our EKS Cluster",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "sum by (namespace) (\r\n  irate(container_network_receive_errors_total[$__rate_interval])\r\n)\r\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Pod Network Transmit Errors",
   "type": "timeseries",
   "description": "Shows Network Transmit Errors for All Pods in our EKS Cluster",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "sum by (pod) (\r\n  irate(container_network_transmit_errors_total[$__rate_interval])\r\n)\r\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Pod Network Receive Errors",
   "type": "timeseries",
   "description": "Shows Total Number of Pod Network Receive Errors in our EKS Cluster",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "sum by (pod) (\r\n  irate(container_network_receive_errors_total[$__rate_interval])\r\n)\r\n",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}